version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_PORT_NUMBER=7000
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 10mb
    ports:
      - '7000:7000'